import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:source_gen/source_gen.dart';

/// Drift 테이블 코드를 생성하는 클래스
class DriftTableGenerator {
  String generate(
    ClassElement element,
    ConstantReader annotation,
    String tableName, {
    required String packageName,
  }) {
    final buffer = StringBuffer();

    // 파일 헤더
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by table_generator\n');
    buffer.writeln('import \'package:drift/drift.dart\';');
    buffer.writeln('import \'package:$packageName/data/datasources/local/database/database.dart\';');

    // Check if there are enum fields and import the original model file
    final enumTypeNames = <String>{};
    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;
      if (_isEnum(field.type)) {
        enumTypeNames.add(field.type.toString().replaceAll('?', ''));
      }
    }

    if (enumTypeNames.isNotEmpty) {
      // tableName is plural (e.g., "sessions"), but file is singular (e.g., "session.dart")
      final singularName = _toSingular(tableName);
      buffer.writeln('import \'package:$packageName/data/definitions/$singularName.dart\';');
      // database.g.dart(part of database.dart)가 enum 타입을 보려면 라이브러리 스코프로
      // 재수출 필요 — import만으로는 database.dart에 타입이 전파되지 않음.
      // 정의 클래스(예: Badge)는 drift row 클래스와 충돌하므로 enum만 show로 한정.
      final shown = (enumTypeNames.toList()..sort()).join(', ');
      buffer.writeln('export \'package:$packageName/data/definitions/$singularName.dart\' show $shown;');
    }

    buffer.writeln();

    // 테이블 클래스 생성
    // Use $ prefix to avoid conflicts with definition classes
    // e.g., tableName "sessions" -> Table class "$Sessions", DataClassName "Session"
    final baseClassName = _toPascalCase(tableName);
    final tableClassName = '\$$baseClassName'; // Prefixed with $ to avoid conflict
    // DataClassName should be singular (e.g., "Session" for the row class)
    final dataClassName = _toPascalCase(_toSingular(tableName));
    buffer.writeln('@DataClassName(\'$dataClassName\')');
    buffer.writeln(
        'class $tableClassName extends Table${_shouldAddTimestamps(annotation) ? ' with TableWithTimestamps' : ''} {');
    // 명시적 tableName — drift가 \$ 접두사 클래스명에서 SQL 테이블명을 유도하면
    // '\$_badge' 같은 깨진 문자열 보간 코드가 생성된다
    buffer.writeln('  @override');
    buffer.writeln('  String get tableName => \'$tableName\';');
    buffer.writeln();

    // 필드들 생성
    final shouldUseTimestampsMixin = _shouldAddTimestamps(annotation);
    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;
      // TableWithTimestamps 믹스인 사용 시 createdAt/updatedAt 필드는 스킵
      if (shouldUseTimestampsMixin && (field.name == 'createdAt' || field.name == 'updatedAt')) {
        continue;
      }
      _generateField(buffer, field);
    }

    // Primary Key 설정
    final primaryKeyFields = _getPrimaryKeyFields(element);
    final hasAutoIncrement = _hasAutoIncrementField(element);

    // Don't override primaryKey if we have an autoIncrement field
    if (primaryKeyFields.isNotEmpty && !hasAutoIncrement) {
      buffer.writeln('\n  @override');
      buffer.writeln('  Set<Column> get primaryKey => {${primaryKeyFields.join(', ')}};');
    }

    buffer.writeln('}');

    return buffer.toString();
  }

  void _generateField(StringBuffer buffer, FieldElement field) {
    // Drift에서는 camelCase를 사용
    final fieldName = field.name;
    if (fieldName == null) return;

    // 어노테이션 처리
    final annotations = field.metadata.annotations;

    // JsonField 어노테이션이 있으면 text로 저장 (JSON 직렬화)
    final hasJsonField = _getAnnotation(annotations, 'JsonField') != null;
    final isEnumField = _isEnum(field.type);
    final columnType = hasJsonField ? 'text' : _getColumnType(field.type);

    buffer.write('  ${_getColumnTypeClass(columnType)} get $fieldName => $columnType()');

    // PrimaryKey
    final primaryKey = _getAnnotation(annotations, 'PrimaryKey');
    if (primaryKey != null) {
      final strategyIndex = primaryKey.getField('strategy')?.getField('index')?.toIntValue();
      if (strategyIndex == 1) {
        // autoIncrement
        buffer.write('.autoIncrement()');
      } else if (strategyIndex == 0) {
        // uuid
        buffer.write('.withDefault(const CustomExpression(\'gen_random_uuid()\'))');
      }
    }

    // References - 단순히 주석으로만 처리 (실제 참조는 SQL에서 처리)
    final references = _getAnnotation(annotations, 'References');
    if (references != null) {
      // References는 주석으로만 표시하고, 실제 외래키는 SQL에서 처리
      final table = references.getField('table')?.toStringValue() ?? '';
      final column = references.getField('column')?.toStringValue() ?? 'id';
      // 참조 정보를 주석으로 추가
      buffer.write(' /* references $table($column) */');
    }

    // Required 어노테이션 확인
    final requiredAnnotation = _getAnnotation(annotations, 'Required');

    // Column 어노테이션 확인
    final columnAnnotation = _getAnnotation(annotations, 'Column');

    // nullable 여부 결정
    bool shouldBeNullable = false;

    if (requiredAnnotation != null) {
      // @Required 어노테이션이 있으면 NOT NULL
      shouldBeNullable = false;
    } else if (columnAnnotation != null) {
      // @Column 어노테이션이 있으면 nullable 속성 확인
      shouldBeNullable = columnAnnotation.getField('nullable')?.toBoolValue() ?? false;
    } else {
      // 어노테이션이 없으면 타입으로 판단
      shouldBeNullable = !_isRequiredType(field.type);
    }

    // nullable 적용
    if (shouldBeNullable) {
      buffer.write('.nullable()');
    }

    // Column 속성 처리
    if (columnAnnotation != null) {
      final unique = columnAnnotation.getField('unique')?.toBoolValue() ?? false;
      final defaultValue = columnAnnotation.getField('defaultValue');

      if (unique) {
        buffer.write('.unique()');
      }

      // For enum fields, use clientDefault with the enum value
      // For other fields, use withDefault with Constant
      if (defaultValue != null && !defaultValue.isNull) {
        if (isEnumField) {
          // Get the enum type name and the default value name
          final enumTypeName = field.type.toString().replaceAll('?', '');
          final defaultValueStr = defaultValue.toStringValue();
          if (defaultValueStr != null) {
            buffer.write('.clientDefault(() => $enumTypeName.$defaultValueStr)');
          }
        } else {
          buffer.write('.withDefault(const Constant(${_formatDefaultValue(defaultValue)}))');
        }
      }
    }

    buffer.writeln('();');
  }

  String _getColumnType(DartType type) {
    // nullable 제거
    final typeName = type.toString().replaceAll('?', '');

    switch (typeName) {
      case 'String':
        return 'text';
      case 'int':
        return 'integer';
      case 'double':
        return 'real';
      case 'bool':
        return 'boolean';
      case 'DateTime':
        return 'dateTime';
      case 'List<int>':
      case 'Uint8List':
        return 'blob';
      default:
        if (_isEnum(type)) {
          return 'intEnum<${type.toString().replaceAll('?', '')}>'; // Enum 타입 지정
        }
        // Map이나 다른 복잡한 타입은 JSON으로 저장
        if (typeName.startsWith('Map<') || typeName.startsWith('List<')) {
          return 'text';
        }
        return 'text'; // 기본값
    }
  }

  bool _isEnum(DartType type) {
    return type.element is EnumElement;
  }

  bool _isRequiredType(DartType type) {
    return !type.toString().endsWith('?');
  }

  String _getColumnTypeClass(String columnType) {
    // drift에서 사용하는 실제 Column 클래스 이름
    switch (columnType) {
      case 'text':
        return 'TextColumn';
      case 'integer':
        return 'IntColumn';
      case 'real':
        return 'RealColumn';
      case 'boolean':
        return 'BoolColumn';
      case 'dateTime':
        return 'DateTimeColumn';
      case 'blob':
        return 'BlobColumn';
      default:
        if (columnType.startsWith('intEnum<')) {
          return 'IntColumn';
        }
        return 'TextColumn';
    }
  }

  dynamic _getAnnotation(Iterable<ElementAnnotation> annotations, String annotationName) {
    try {
      return annotations
          .map((a) => a.computeConstantValue())
          .firstWhere((v) => v?.type?.element?.name == annotationName, orElse: () => null);
    } catch (_) {
      return null;
    }
  }

  List<String> _getPrimaryKeyFields(ClassElement element) {
    final primaryKeys = <String>[];

    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      final hasPrimaryKey =
          field.metadata.annotations.any((a) => a.computeConstantValue()?.type?.element?.name == 'PrimaryKey');

      if (hasPrimaryKey && field.name != null) {
        primaryKeys.add(field.name!);
      }
    }

    return primaryKeys;
  }

  String _formatDefaultValue(dynamic value) {
    if (value.toStringValue() != null) {
      return '\'${value.toStringValue()}\'';
    } else if (value.toBoolValue() != null) {
      return value.toBoolValue().toString();
    } else if (value.toIntValue() != null) {
      return value.toIntValue().toString();
    } else if (value.toDoubleValue() != null) {
      return value.toDoubleValue().toString();
    }
    return 'null';
  }

  bool _shouldAddTimestamps(ConstantReader annotation) {
    return annotation.peek('timestamps')?.boolValue ?? true;
  }

  String _toPascalCase(String text) {
    return text.split('_').map((word) => word.substring(0, 1).toUpperCase() + word.substring(1)).join('');
  }

  bool _hasAutoIncrementField(ClassElement element) {
    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      final primaryKey = _getAnnotation(field.metadata.annotations.toList(), 'PrimaryKey');
      if (primaryKey != null) {
        final strategyIndex = primaryKey.getField('strategy')?.getField('index')?.toIntValue();
        if (strategyIndex == 1) {
          // autoIncrement strategy
          return true;
        }
      }
    }
    return false;
  }

  /// Convert plural table name to singular for file imports
  /// e.g., "sessions" -> "session", "categories" -> "category", "daily_stats" -> "daily_stats"
  String _toSingular(String tableName) {
    // Words that should NOT be singularized (collective/uncountable nouns)
    const preserveAsIs = {
      'settings',
      'news',
      'analytics',
      'statistics',
      'mathematics',
      'physics',
      'economics',
      'electronics',
    };

    if (preserveAsIs.contains(tableName)) {
      return tableName;
    }

    // Handle special cases for common pluralization patterns
    if (tableName.endsWith('ies')) {
      // categories -> category
      return '${tableName.substring(0, tableName.length - 3)}y';
    } else if (tableName.endsWith('es') &&
               (tableName.endsWith('sses') || tableName.endsWith('xes') || tableName.endsWith('zes') ||
                tableName.endsWith('ches') || tableName.endsWith('shes'))) {
      // classes -> class, boxes -> box
      return tableName.substring(0, tableName.length - 2);
    } else if (tableName.endsWith('s') && !tableName.endsWith('ss') && !tableName.endsWith('_stats')) {
      // sessions -> session, users -> user
      // But preserve: daily_stats -> daily_stats
      return tableName.substring(0, tableName.length - 1);
    }
    return tableName;
  }
}
