import 'package:analyzer/dart/element/element.dart';
import 'package:source_gen/source_gen.dart';

/// Freezed 모델 코드를 생성하는 클래스
class ModelGenerator {
  String generate(
    ClassElement element,
    ConstantReader annotation,
    String tableName, {
    String? originalFileName,
    required String packageName,
  }) {
    final buffer = StringBuffer();
    final className = element.name;
    if (className == null) return '';

    // 파일 헤더
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by table_generator\n');
    buffer.writeln('import \'package:freezed_annotation/freezed_annotation.dart\';');

    // List 필드가 있으면 dart:convert import 추가
    final listFields = _getListFields(element);
    if (listFields.isNotEmpty) {
      buffer.writeln('import \'dart:convert\';');
    }

    // Check if we need to import the original file (for enums)
    final enumTypes = _getEnumTypes(element);
    if (enumTypes.isNotEmpty) {
      // 원본 파일은 definitions 폴더에 있음
      buffer.writeln('import \'package:$packageName/data/definitions/$tableName.dart\';');
    }

    // Use tableName for file names to maintain consistency
    buffer.writeln('\npart \'$tableName.model.freezed.dart\';');
    buffer.writeln('part \'$tableName.model.g.dart\';\n');

    // Freezed 클래스 생성 (Freezed 3.0.0+ requires abstract or sealed)
    buffer.writeln('@freezed');
    buffer.writeln('abstract class ${className}Model with _\$${className}Model {');
    buffer.writeln('  const ${className}Model._();');
    buffer.writeln();
    buffer.writeln('  const factory ${className}Model({');

    // 필드들 생성 및 타임스탬프 필드 존재 확인
    bool hasCreatedAt = false;
    bool hasUpdatedAt = false;

    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      // 타임스탬프 필드 존재 확인
      if (field.name == 'createdAt') hasCreatedAt = true;
      if (field.name == 'updatedAt') hasUpdatedAt = true;

      _generateModelField(buffer, field);
    }

    // 타임스탬프 필드 추가 (이미 존재하지 않는 경우만)
    if (_shouldAddTimestamps(annotation)) {
      if (!hasCreatedAt) {
        buffer.writeln('    @JsonKey(name: \'created_at\') DateTime? createdAt,');
      }
      if (!hasUpdatedAt) {
        buffer.writeln('    @JsonKey(name: \'updated_at\') DateTime? updatedAt,');
      }
    }

    buffer.writeln('  }) = _${className}Model;');
    buffer.writeln();

    // fromJson/toJson
    buffer.writeln('  factory ${className}Model.fromJson(Map<String, dynamic> json) =>');
    buffer.writeln('      _\$${className}ModelFromJson(json);');
    buffer.writeln();

    // 데이터베이스 변환 메서드
    buffer.writeln('  // 데이터베이스 변환 메서드');
    buffer.writeln('  Map<String, dynamic> toDatabaseMap() {');
    buffer.writeln('    final map = toJson();');
    buffer.writeln('    // 필드명을 snake_case로 변환 및 List 필드 JSON 직렬화');
    buffer.writeln('    final dbMap = <String, dynamic>{};');
    buffer.writeln('    map.forEach((key, value) {');
    buffer.writeln('      final snakeKey = key.replaceAllMapped(');
    buffer.writeln('        RegExp(r\'([A-Z])\'),');
    buffer.writeln('        (match) => \'_\${match.group(1)!.toLowerCase()}\',');
    buffer.writeln('      );');

    // List 필드 JSON 직렬화 추가
    if (listFields.isNotEmpty) {
      buffer.writeln('      // List 타입은 JSON 문자열로 변환 (Drift TextColumn 저장용)');
      final listFieldNames = listFields.map((f) => _getDbName(f)).toList();
      buffer.write('      if (');
      for (var i = 0; i < listFieldNames.length; i++) {
        if (i > 0) buffer.write(' || ');
        buffer.write('snakeKey == \'${listFieldNames[i]}\'');
      }
      buffer.writeln(') {');
      buffer.writeln('        if (value != null) {');
      buffer.writeln('          dbMap[snakeKey] = jsonEncode(value);');
      buffer.writeln('        } else {');
      buffer.writeln('          dbMap[snakeKey] = null;');
      buffer.writeln('        }');
      buffer.writeln('      } else {');
      buffer.writeln('        dbMap[snakeKey] = value;');
      buffer.writeln('      }');
    } else {
      buffer.writeln('      dbMap[snakeKey] = value;');
    }

    buffer.writeln('    });');
    buffer.writeln('    return dbMap;');
    buffer.writeln('  }');
    buffer.writeln();

    buffer.writeln('  factory ${className}Model.fromDatabaseMap(Map<String, dynamic> map) {');
    buffer.writeln('    // snake_case 필드명을 그대로 사용 (fromJson이 snake_case를 기대함)');
    buffer.writeln('    final jsonMap = <String, dynamic>{};');
    buffer.writeln();

    // DateTime 필드 목록 생성
    final dateTimeFields = _getDateTimeFields(element);
    if (dateTimeFields.isNotEmpty) {
      final dateTimeFieldNames = dateTimeFields.map((f) => _getDbName(f)).toList();
      buffer.writeln('    // DateTime 필드 목록 (SQLite에서 int로 저장됨)');
      buffer.writeln('    const dateTimeFields = {');
      for (final name in dateTimeFieldNames) {
        buffer.writeln("      '$name',");
      }
      buffer.writeln('    };');
      buffer.writeln();
    }

    buffer.writeln('    map.forEach((key, value) {');

    // Bool 필드와 List 필드에 대한 특별 처리
    final boolFields = _getBoolFields(element);
    final listFieldsForRead = _getListFields(element);

    var hasCondition = false;

    // Bool 필드 처리
    if (boolFields.isNotEmpty) {
      final boolFieldNames = boolFields.map((f) => _getDbName(f)).toList();
      buffer.writeln('      // SQLite에서 bool 값은 0/1로 저장되므로 변환 필요');
      buffer.write('      if ((');
      for (var i = 0; i < boolFieldNames.length; i++) {
        if (i > 0) buffer.write(' || ');
        buffer.write("key == '${boolFieldNames[i]}'");
      }
      buffer.writeln(') && value is int) {');
      buffer.writeln('        jsonMap[key] = value == 1;');
      hasCondition = true;
    }

    // List 필드 처리 (String 및 BLOB 모두 지원)
    if (listFieldsForRead.isNotEmpty) {
      final listFieldNames = listFieldsForRead.map((f) => _getDbName(f)).toList();
      if (hasCondition) {
        buffer.write('      } else if (');
      } else {
        buffer.writeln('      // JSON 문자열로 저장된 List 필드 역직렬화 (TEXT 및 BLOB 모두 지원)');
        buffer.write('      if (');
      }
      for (var i = 0; i < listFieldNames.length; i++) {
        if (i > 0) buffer.write(' || ');
        buffer.write("key == '${listFieldNames[i]}'");
      }
      buffer.writeln(') {');
      buffer.writeln(
          '        // Handle both String (TEXT column) and List<int> (BLOB column for backwards compatibility)');
      buffer.writeln('        if (value is String) {');
      buffer.writeln('          jsonMap[key] = jsonDecode(value);');
      buffer.writeln('        } else if (value is List<int>) {');
      buffer.writeln('          // BLOB data - convert bytes to string then decode JSON');
      buffer.writeln('          final str = String.fromCharCodes(value);');
      buffer.writeln('          try {');
      buffer.writeln('            jsonMap[key] = jsonDecode(str);');
      buffer.writeln('          } catch (_) {');
      buffer.writeln('            jsonMap[key] = [];');
      buffer.writeln('          }');
      buffer.writeln('        } else {');
      buffer.writeln('          jsonMap[key] = value ?? [];');
      buffer.writeln('        }');
      hasCondition = true;
    }

    // DateTime 필드 처리 (초/밀리초 범위 기반 변환)
    if (dateTimeFields.isNotEmpty) {
      if (hasCondition) {
        buffer.writeln('      } else if (dateTimeFields.contains(key)) {');
      } else {
        buffer.writeln('      if (dateTimeFields.contains(key)) {');
      }
      buffer.writeln('        // DateTime 필드 처리: int(초 또는 밀리초) 또는 String(ISO8601) 지원');
      buffer.writeln('        if (value == null) {');
      buffer.writeln('          jsonMap[key] = null;');
      buffer.writeln('        } else if (value is int) {');
      buffer.writeln('          // Drift는 DateTime을 초(seconds)로 저장하지만,');
      buffer.writeln('          // 일부 경로에서 밀리초로 저장될 수 있으므로 범위로 판별');
      buffer.writeln('          const minValidSec = 946684800;    // 2000-01-01 (초)');
      buffer.writeln('          const maxValidSec = 4102444800;   // 2100-01-01 (초)');
      buffer.writeln('          const minValidMs = 946684800000;  // 2000-01-01 (밀리초)');
      buffer.writeln('          const maxValidMs = 4102444800000; // 2100-01-01 (밀리초)');
      buffer.writeln();
      buffer.writeln('          DateTime? dateTime;');
      buffer.writeln('          if (value >= minValidSec && value <= maxValidSec) {');
      buffer.writeln('            dateTime = DateTime.fromMillisecondsSinceEpoch(value * 1000);');
      buffer.writeln('          } else if (value >= minValidMs && value <= maxValidMs) {');
      buffer.writeln('            dateTime = DateTime.fromMillisecondsSinceEpoch(value);');
      buffer.writeln('          } else if (value > 0) {');
      buffer.writeln('            if (value >= 10000000000) {');
      buffer.writeln('              dateTime = DateTime.fromMillisecondsSinceEpoch(value);');
      buffer.writeln('            } else {');
      buffer.writeln('              dateTime = DateTime.fromMillisecondsSinceEpoch(value * 1000);');
      buffer.writeln('            }');
      buffer.writeln('          }');
      buffer.writeln('          jsonMap[key] = dateTime?.toIso8601String();');
      buffer.writeln('        } else if (value is String) {');
      buffer.writeln('          jsonMap[key] = value;');
      buffer.writeln('        } else {');
      buffer.writeln('          jsonMap[key] = null;');
      buffer.writeln('        }');
      hasCondition = true;
    }

    // 기본 처리
    if (hasCondition) {
      buffer.writeln('      } else {');
      buffer.writeln('        jsonMap[key] = value;');
      buffer.writeln('      }');
    } else {
      buffer.writeln('      jsonMap[key] = value;');
    }

    buffer.writeln('    });');
    buffer.writeln('    ');
    buffer.writeln('    // null 값 처리 - 필수 필드들에 기본값 설정 (snake_case 사용)');
    _generateNullHandlingSnakeCase(buffer, element);
    buffer.writeln('    ');
    buffer.writeln('    return ${className}Model.fromJson(jsonMap);');
    buffer.writeln('  }');

    buffer.writeln('}');

    return buffer.toString();
  }

  void _generateModelField(StringBuffer buffer, FieldElement field) {
    final fieldName = field.name;
    final fieldType = field.type.getDisplayString();

    // 어노테이션 확인
    final annotations = field.metadata.annotations.toList();
    final hasDefaultValue = _hasDefaultValue(annotations);
    final isRequired =
        (_hasRequiredAnnotation(annotations) || _hasPrimaryKeyAnnotation(annotations)) && !hasDefaultValue;

    // 어노테이션을 한 줄에 모으기
    final annotationParts = <String>[];

    // @Default 어노테이션 추가 (필요한 경우)
    if (hasDefaultValue && !fieldType.endsWith('?')) {
      final defaultValue = _getDefaultValue(annotations);
      if (defaultValue != null) {
        annotationParts.add('@Default($defaultValue)');
      }
    }

    // JsonKey 어노테이션 추가 (필요한 경우)
    final dbName = _getDbName(field);
    if (dbName != fieldName) {
      annotationParts.add('@JsonKey(name: \'$dbName\')');
    }

    // 어노테이션과 필드를 한 줄에 작성
    final annotationLine = annotationParts.isNotEmpty ? '    ${annotationParts.join(' ')} ' : '    ';

    // 필드 생성
    if (isRequired && !fieldType.endsWith('?')) {
      buffer.writeln('${annotationLine}required $fieldType $fieldName,');
    } else if (!fieldType.endsWith('?') && !hasDefaultValue) {
      // Non-nullable field without default value should be required
      buffer.writeln('${annotationLine}required $fieldType $fieldName,');
    } else {
      buffer.writeln('$annotationLine$fieldType $fieldName,');
    }
  }

  bool _hasRequiredAnnotation(Iterable<ElementAnnotation> annotations) {
    return annotations.any((a) => a.computeConstantValue()?.type?.element?.name == 'Required');
  }

  bool _hasPrimaryKeyAnnotation(Iterable<ElementAnnotation> annotations) {
    return annotations.any((a) => a.computeConstantValue()?.type?.element?.name == 'PrimaryKey');
  }

  bool _hasDefaultValue(Iterable<ElementAnnotation> annotations) {
    for (final annotation in annotations) {
      final value = annotation.computeConstantValue();
      if (value?.type?.element?.name == 'Column') {
        final defaultValue = value?.getField('defaultValue');
        if (defaultValue != null && !defaultValue.isNull) {
          return true;
        }
      }
    }
    return false;
  }

  String _getDbName(FieldElement field) {
    final columnAnnotation = field.metadata.annotations.map((a) => a.computeConstantValue()).firstWhere(
          (v) => v?.type?.element?.name == 'Column' || v?.type?.element?.name == 'Required',
          orElse: () => null,
        );

    if (columnAnnotation != null) {
      final dbName = columnAnnotation.getField('dbName')?.toStringValue();
      if (dbName != null) return dbName;
    }

    return _toSnakeCase(field.name ?? '');
  }

  List<String> _getEnumTypes(ClassElement element) {
    final enumTypes = <String>[];

    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      final type = field.type;
      if (type.element is EnumElement) {
        final enumName = type.getDisplayString();
        if (!enumTypes.contains(enumName)) {
          enumTypes.add(enumName);
        }
      }
    }

    return enumTypes;
  }

  bool _shouldAddTimestamps(ConstantReader annotation) {
    return annotation.peek('timestamps')?.boolValue ?? true;
  }

  String? _getDefaultValue(Iterable<ElementAnnotation> annotations) {
    for (final annotation in annotations) {
      final value = annotation.computeConstantValue();
      if (value?.type?.element?.name == 'Column') {
        final defaultValue = value?.getField('defaultValue');
        if (defaultValue != null && !defaultValue.isNull) {
          // Handle different types of default values
          final boolValue = defaultValue.toBoolValue();
          if (boolValue != null) {
            return boolValue.toString();
          }

          final intValue = defaultValue.toIntValue();
          if (intValue != null) {
            return intValue.toString();
          }

          final doubleValue = defaultValue.toDoubleValue();
          if (doubleValue != null) {
            return doubleValue.toString();
          }

          final stringValue = defaultValue.toStringValue();
          if (stringValue != null) {
            // Escape string for Dart code
            return "'${stringValue.replaceAll("'", "\\'")}'";
          }

          final listValue = defaultValue.toListValue();
          if (listValue != null) {
            return 'const []';
          }

          final mapValue = defaultValue.toMapValue();
          if (mapValue != null) {
            return 'const {}';
          }

          // For complex objects or expressions, return the string representation
          return defaultValue.toString();
        }
      }
    }
    return null;
  }

  List<FieldElement> _getBoolFields(ClassElement element) {
    final boolFields = <FieldElement>[];

    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      // bool 타입인지 확인
      final typeName = field.type.toString().replaceAll('?', '');
      if (typeName == 'bool') {
        boolFields.add(field);
      }
    }

    return boolFields;
  }

  List<FieldElement> _getListFields(ClassElement element) {
    final listFields = <FieldElement>[];

    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      // List 타입인지 확인
      final typeName = field.type.toString().replaceAll('?', '');
      if (typeName.startsWith('List<')) {
        listFields.add(field);
      }
    }

    return listFields;
  }

  List<FieldElement> _getDateTimeFields(ClassElement element) {
    final dateTimeFields = <FieldElement>[];

    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      // DateTime 타입인지 확인
      final typeName = field.type.toString().replaceAll('?', '');
      if (typeName == 'DateTime') {
        dateTimeFields.add(field);
      }
    }

    return dateTimeFields;
  }

  String _toSnakeCase(String text) {
    final result = text.replaceAllMapped(
      RegExp('([A-Z])'),
      (match) => '_${match.group(1)!.toLowerCase()}',
    );

    // 첫 글자가 '_'로 시작하면 제거
    return result.startsWith('_') ? result.substring(1) : result;
  }

  void _generateNullHandlingSnakeCase(StringBuffer buffer, ClassElement element) {
    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      final fieldName = _getDbName(field); // snake_case 필드명 사용
      final fieldType = field.type.toString();
      final isNullable = fieldType.endsWith('?');
      final fieldAnnotations = field.metadata.annotations;
      final hasDefault = _hasDefaultValue(fieldAnnotations);
      final isRequired =
          (_hasRequiredAnnotation(fieldAnnotations) || _hasPrimaryKeyAnnotation(fieldAnnotations)) && !hasDefault;

      // 필수 필드이면서 nullable이 아닌 경우에만 처리
      if ((isRequired || !isNullable) && !hasDefault) {
        final baseType = fieldType.replaceAll('?', '');
        String defaultValue;

        // 타입별 기본값 설정
        if (baseType == 'String') {
          defaultValue = "''";
        } else if (baseType == 'int') {
          defaultValue = '0';
        } else if (baseType == 'double') {
          defaultValue = '0.0';
        } else if (baseType == 'bool') {
          defaultValue = 'false';
        } else if (baseType == 'DateTime') {
          defaultValue = 'DateTime.now().toIso8601String()';
        } else if (baseType.startsWith('List<')) {
          defaultValue = '[]';
        } else if (baseType.startsWith('Map<')) {
          defaultValue = '{}';
        } else {
          // 그 외의 타입은 처리하지 않음
          continue;
        }

        buffer.writeln("    jsonMap['$fieldName'] ??= $defaultValue;");
      }
    }
  }
}
