import 'package:analyzer/dart/element/element.dart';

/// Repository 코드를 생성하는 클래스
class RepositoryGenerator {
  String generate(ClassElement element, String tableName, {required String packageName}) {
    final buffer = StringBuffer();
    final className = element.name;
    if (className == null) return '';
    final modelName = '${className}Model';
    // tableName is already plural (e.g., "sessions"), use it directly
    final tablePluralName = tableName;

    // Detect primary key type and nullability
    final idType = _getPrimaryKeyType(element);
    final isIdNullable = _isPrimaryKeyNullable(element);
    final idAccessor = isIdNullable ? 'model.id!' : 'model.id';

    // 파일 헤더
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by table_generator\n');

    // imports
    buffer.writeln('import \'package:flutter_riverpod/flutter_riverpod.dart\';');
    buffer.writeln('import \'package:$packageName/data/datasources/database_datasource.dart\';');
    buffer.writeln('import \'package:$packageName/data/generated/models/${_toSnakeCase(className)}.model.dart\';');
    buffer.writeln('import \'package:$packageName/data/core/repositories/base_repository.dart\';');
    buffer.writeln('import \'package:$packageName/data/core/repositories/repository_providers.dart\';\n');

    // Repository 클래스
    buffer.writeln('/// $className 관련 데이터 처리를 담당하는 Repository');
    buffer.writeln('class ${className}Repository extends BaseRepository<$modelName, $idType> {');
    buffer.writeln('  ');
    buffer.writeln('  // 테이블 이름');
    buffer.writeln('  static const String _tableName = \'$tablePluralName\';');
    buffer.writeln('  ');
    buffer.writeln('  ${className}Repository({');
    buffer.writeln('    required DatabaseDataSource database,');
    buffer.writeln('  }) : super(');
    buffer.writeln('         database: database,');
    buffer.writeln('         tableName: _tableName,');
    buffer.writeln('         fromDatabaseMap: $modelName.fromDatabaseMap,');
    buffer.writeln('         fromJson: $modelName.fromJson,');
    buffer.writeln('         toDatabaseMap: (model) => model.toDatabaseMap(),');
    buffer.writeln('         toJson: (model) => model.toJson(),');
    buffer.writeln('         getId: (model) => $idAccessor,');
    buffer.writeln('       );');
    buffer.writeln();

    // BaseRepository에서 CRUD 메서드 상속 (getById, getAll, create, update, delete, deleteMany)
    // 추가적인 관계 메서드들만 생성
    _generateRelationMethods(buffer, element, className, modelName);

    buffer.writeln('}');
    buffer.writeln();

    // Provider 추가
    final providerName = '${_toCamelCase(className)}RepositoryProvider';
    buffer.writeln();
    buffer.writeln('// ============================================');
    buffer.writeln('// PROVIDER SECTION');
    buffer.writeln('// ============================================');
    buffer.writeln('// To use this provider, add the following import to your code:');
    buffer.writeln('// import \'package:$packageName/data/definitions/${_toSnakeCase(className)}.repository.dart\';');
    buffer.writeln('//');
    buffer.writeln('// Then you can use: ref.watch($providerName)');
    buffer.writeln('// ============================================');
    buffer.writeln();
    buffer.writeln('/// $className Repository Provider');
    buffer.writeln('final $providerName = Provider<${className}Repository>((ref) {');
    buffer.writeln('  final database = ref.watch(databaseProvider);');
    buffer.writeln();
    buffer.writeln('  return ${className}Repository(');
    buffer.writeln('    database: database,');
    buffer.writeln('  );');
    buffer.writeln('});');

    return buffer.toString();
  }

  void _generateRelationMethods(StringBuffer buffer, ClassElement element, String className, String modelName) {
    // References 어노테이션이 있는 필드 찾기
    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      final references = field.metadata.annotations
          .map((a) => a.computeConstantValue())
          .firstWhere((v) => v?.type?.element?.name == 'References', orElse: () => null);

      if (references != null) {
        final fieldName = field.name;
        if (fieldName == null) continue;

        // getBy{FieldName} 메서드 생성
        buffer.writeln('  /// Get all $className by ${_toReadableName(fieldName)}');
        buffer.writeln(
          '  Future<List<$modelName>> getBy${_toPascalCase(fieldName)}(String ${_toCamelCase(fieldName)}) async {',
        );
        buffer.writeln('    try {');
        buffer.writeln('      final results = await database.findMany(');
        buffer.writeln('        _tableName,');
        buffer.writeln('        where: {\'${_toSnakeCase(fieldName)}\': ${_toCamelCase(fieldName)}},');
        buffer.writeln('      );');
        buffer.writeln('      return results');
        buffer.writeln('          .map((map) => $modelName.fromDatabaseMap(map))');
        buffer.writeln('          .toList();');
        buffer.writeln('    } catch (e) {');
        buffer.writeln(
          '      throw RepositoryException(\'Failed to get $className by $fieldName\', originalError: e);',
        );
        buffer.writeln('    }');
        buffer.writeln('  }');
        buffer.writeln();
      }
    }
  }

  String _toSnakeCase(String text) {
    final result = text.replaceAllMapped(RegExp('([A-Z])'), (match) => '_${match.group(1)!.toLowerCase()}');

    // 첫 글자가 '_'로 시작하면 제거
    return result.startsWith('_') ? result.substring(1) : result;
  }

  String _toPascalCase(String text) {
    return text.substring(0, 1).toUpperCase() + text.substring(1);
  }

  String _toCamelCase(String text) {
    return text.substring(0, 1).toLowerCase() + text.substring(1);
  }

  String _toReadableName(String text) {
    return text.replaceAllMapped(RegExp('([A-Z])'), (match) => ' ${match.group(1)!.toLowerCase()}').trim();
  }

  String _getPrimaryKeyType(ClassElement element) {
    // Find the field with @PrimaryKey annotation
    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      final hasPrimaryKey = field.metadata.annotations.any(
        (a) => a.computeConstantValue()?.type?.element?.name == 'PrimaryKey',
      );

      if (hasPrimaryKey) {
        final type = field.type.getDisplayString();
        // Remove nullable suffix if present
        return type.endsWith('?') ? type.substring(0, type.length - 1) : type;
      }
    }

    // Default to String if no primary key found
    return 'String';
  }

  bool _isPrimaryKeyNullable(ClassElement element) {
    // Find the field with @PrimaryKey annotation and check if it's nullable
    for (final field in element.fields) {
      if (field.isStatic || field.isSynthetic) continue;

      final hasPrimaryKey = field.metadata.annotations.any(
        (a) => a.computeConstantValue()?.type?.element?.name == 'PrimaryKey',
      );

      if (hasPrimaryKey) {
        final type = field.type.getDisplayString();
        return type.endsWith('?');
      }
    }

    return false;
  }
}
