include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - always_declare_return_types

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
